### ISSUE TITLE
feat: Router 구현 , layout 구현 및 GlobalStyle 적용

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/wanted-preonboarding-tripbtoz#1]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: globalstyle 적용 & layout 구현

## TODO
- [x] styled-component globalstyle 적용
- [x] style-theme 적용
- [x] router 적용
- [x] outlet을 사용한 layout 적용

## Labels
Estimated time: E: `1h`
Group : `client`
