### ISSUE TITLE
feat: search modal display / data 관련 state 추가

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/wanted-preonboarding-tripbtoz#27]
## ISSUE
- Group: `client`
- Type:  `feature`
- Detail: add data state

## TODO
- [x] SearchBar 컴포넌트에  modal sate 추가
- [x] SearchBar 컴포넌트에  searchData state추가
- [x] Calendar SearchBar state 적용
- [x] search.ts type추가
- [x] getdate 생성

## Labels
Estimated time: E: `3h`
Group : `client`
