### ISSUE TITLE
feat: handleSearch 함수 적용 및 width변동에 따른 scorll 제어 

### ISSUE THREAD

**Issue by mrlee323** [wanted-group-4/wanted-preonboarding-tripbtoz#59]
## ISSUE
- Group: `client`
- Type:  `feature`
- Detail:  add handleSearch function 

## TODO
- [x] handleSearch 함수 적용
- [x] layout hader fixed 추가
- [x] search date default value를 location hook으로 이동
- [x] width변경시 scroll제어
- [x] search 실행시 modal 닫힘 

## Labels
Estimated time: E: `1h`
Group : `client`
