### ISSUE TITLE
feat: Landing 페이지 UI 구현

### ISSUE THREAD

**Issue by JiehoonPark** [wanted-group-4/wanted-preonboarding-tripbtoz#6]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: landing페이지

## TODO
- [x] 호텔 card component 적용
- [x] 페이지에 따라 헤더 고정 시키기
- [x] 반응형 UI 구현

## Labels
Group : `client`
